### ISSUE TITLE
Invalid Response for everything

### ISSUE THREAD

**Issue by iamsabet** [VictorMRojas/g4f-ts#35]
it used to work few days ago no problem , but since yesterday it errors on everything, chat complition , translate ... 
with any options or providers
tried using different dns and vpns, no change

v@1.4.6
example test code 
```
import { G4F } from "g4f"
import { JSDOM } from "jsdom";

const g4f = new G4F()

const messages = [
    { role: "system", content: "You're an expert bot in poetry." },
    { role: "user", content: "Let's see, write a single paragraph-long poem for me." },
];
const options = {
    provider: g4f.providers.GPT,
    model: "gpt-4",
    debug: true,
    output: (text: string) => {
        return "result :" + text;
    }
};


(async () => {
    try {
        const text = await g4f.chatCompletion(messages, options);
        console.log(text);
    } catch (e) {
        console.error(e)
    }
})();
```
and i have this  error printed

Debugger attached.
[provider] ┬╗ ΓêÜ  success   Provider found: GPT

[model] ┬╗ ΓêÜ  success   Using the model: gpt-4

[provider] ┬╗ ...  awaiting  Fetching data from the provider: GPT
Error: Invalid response.
    at GPT.handleResponse (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:120:13)
    at handleStream (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:50:12)
    at C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:113:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatCompletionHandler.getText (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:1179:18)
    at async ChatCompletionHandler.runOutput (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:1219:14)
    at async ChatCompletionHandler.runPreprocessing (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:1191:14)
    at async ChatCompletionHandler.generateCompletion (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:1170:14)
    at async G4F.chatCompletion (C:\Users\Sabet\Desktop\projects\AIT\node_modules\g4f\dist\index.js:1491:12)
    at async <anonymous> (C:\Users\Sabet\Desktop\projects\AIT\src\actions\translate.actions.ts:28:22)
Queue check

I appreciate some guide or help, thanks

**Comment by KiyoEditz** [comment]
We're same bro. I think the code has expired.

**Comment by VictorMRojas** [comment]
Hello!, thank you for reporting the problem, I am currently working on a solution to bring these functionalities back to life, I do it in my free time because I don't have much time due to work, but I promise that new things will come

**Comment by YOUDYPARRA** [comment]
Hi,  i have same error log, can i help @VictorMRojas. I'd love to help out and learn along the way!. Can't wait to hear from you

**Comment by reza-chilli** [comment]
Hello
is anybody working on this issue?
